// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/Contact/Contact.vue')['default']
    ContactMobile: typeof import('./src/components/Contact/ContactMobile.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Mine: typeof import('./src/components/Mine/Mine.vue')['default']
    MineMobile: typeof import('./src/components/Mine/MineMobile.vue')['default']
    MyInfo: typeof import('./src/components/MyInfo/MyInfo.vue')['default']
    MyInfoMobile: typeof import('./src/components/MyInfo/MyInfoMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/User/User.vue')['default']
    UserMobile: typeof import('./src/components/User/UserMobile.vue')['default']
    VanImage: typeof import('vant/es')['Image']
    VanStep: typeof import('vant/es')['Step']
    VanSteps: typeof import('vant/es')['Steps']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
